name: Terraform Execution
on:
  push:
    branches: [feat]
  # pull_request:
jobs:
  build:
    if: github.repository == 'terraform_code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"
  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello2"
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello3"
  deploy:
    needs: [test1,test2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello3"