name: Terraform Execution

on:
  push:
    branches: [feature]
  # pull_request:

  stages:
    - stage: STAGE 1
      jobs:
        J1:
          runs-on: ubuntu-latest
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          steps:
            - uses: actions/checkout@v3
            - id: STEP 1
              run: echo "STAGE1 JOB1 STEP1 executed"
            - id: STEP 2
              run: echo "STAGE1 JOB1 STEP2 executed"
        J2:
          runs-on: ubuntu-latest
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          steps:
            - uses: actions/checkout@v3
            - id: STEP 1
              run: echo "STAGE1 JOB2 STEP1 executed"
            - id: STEP 2
              run: echo "STAGE1 JOB2 STEP2 executed"

    - stage: STAGE 2
      jobs:
        J1:
          runs-on: ubuntu-latest
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          steps:
            - uses: actions/checkout@v3
            - id: STEP 1
              run: echo "STAGE2 JOB1 STEP1 executed"
            - id: STEP 2
              run: echo "STAGE2 JOB1 STEP2 executed"
        J2:
          runs-on: ubuntu-latest
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          steps:
            - uses: actions/checkout@v3
            - id: STEP 1
              run: echo "STAGE2 JOB2 STEP1 executed"
            - id: STEP 2
              run: echo "STAGE2 JOB2 STEP2 executed"






              ##########


              #######