name: Terraform Execution
on:
  push:
    branches: [feat]
  # pull_request:
jobs:
  runs-on: ubuntu-latest
    job1:
      # runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo "hello"
    job2:
      # runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo "hello2"
    job3:
      # runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo "hello3"