name: terraform-execution
on:
  push:
    branches: [master]
  # pull_request:
  repository_dispatch:
#     types:
#       - deploy_service
jobs:
  build:
    if: github.repository == 'nikhil1828/terraform_code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"
  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello2"
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello3"
  deploy:
    needs: [test1,test2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello3"
