name: print_environment_variables

on:
  push: 
    branch: [feat]

jobs:
  job1: 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - run: env
####


########