name: print_environment_variables

on:
  push: 
    branches: [feat]

jobs:
  job1: 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      new: test
    steps:
    - run: |
        echo "new =test_three" >> $GITHUB_ENV
        env
        echo "${{env.new}}"

    - run: touch env_vars.txt

    - run: env >> env_vars.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: env_vars.txt