name: Trigger Deploy

on:
  # push:
  #   branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      DEPLOYMENT_NOTIFICATION_URL: https://api.github.com/repos/nikhil1828/test_repo/dispatches
    runs-on: self-hosted
    steps:
      - run: | 
          hostname
          touch newfile
          cat /proc/os-release
          #AUTH_HEADER="Authorization: bearer ${{ secrets.GIT_PAT }}"
          #PAYLOAD='{ "event_type": "deploy_service" }'
          #curl --request POST "$DEPLOYMENT_NOTIFICATION_URL" --header "$AUTH_HEADER" --header "Content-Type: application/json" --data-raw "$PAYLOAD" -f -i
