name: Trigger Deploy

on:
  push:
    branches: [feat]

jobs:
  deploy:
    env: 
      SERVICE_NAME: starter-service
      DEPLOYMENT_NOTIFICATION_URL: https://api.github.com/repos/nikhil1828/terraform_code/action/workflows/terraform-execution/dispatches
    runs-on: ubuntu-latest
    steps:
      - run: | 
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          PAYLOAD='{ "event_type": "deploy_service", "client_payload": { "service": "'"$SERVICE_NAME"'", "version": "'"$RELEASE_VERSION"'" }}'
          curl --request POST "$DEPLOYMENT_NOTIFICATION_URL" --header "$AUTH_HEADER" --header "Content-Type: application/json" --data-raw "$PAYLOAD" -f -i