name: user_input

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: choose name
        options:
        - nikhil
        - salman
      message: 
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "S{{ github.event.inputs.name}}"
      - run: echo "${{ github.event.inputs.message}}"
      - run: echo "S{{ github.event.inputs.emoji}}"
      - run: echo "${{ github.event.inputs.environment}}"